serverType: march
httpPort: 8086
metricPort: 9096
log:
  level: info
  path: ./logs
jwt:
  secret: YOUR-JWT-SECRET
  exp: 7
domain:
  user:
    name: user/v1
    loadBalance: true
etcd:
  addrs: ["127.0.0.1:2379"]
  register:
    addr: 127.0.0.1:12600
    domain: march
    version: v1
    weight: 10
    ttl: 30
  rwTimeout: 3
  dialTimeout: 3
database:
  mongo:
    url: mongodb://localhost:27017
    db: go_mahjong
    username: ""
    password: ""
    minPoolSize: 10
    maxPoolSize: 100
  redis:
    addr: localhost:6379
    clusterAddrs: []
    password: ""
    poolSize: 100
    minIdleConns: 10
    host: localhost
    port: 6379
nats:
  url: nats://127.0.0.1:4222

marchPool:
  - poolID: "classic:rank4:novice"
    strategy: "classic:poll"
    batchSize: 30
    internal: 3000
  - poolID: "classic:rank4:guard"
    strategy: "classic:poll"
    batchSize: 30
    internal: 3000
  - poolID: "classic:rank4:hero"
    strategy: "classic:poll"
    batchSize: 30
    internal: 3000
  - poolID: "classic:rank4:saint"
    strategy: "classic:poll"
    batchSize: 30
    internal: 3000
  - poolID: "classic:rank4:sky"
    strategy: "classic:poll"
    batchSize: 30
    internal: 3000

  - poolID: "classic:casual4"
    strategy: "classic:poll"
    batchSize: 30
    internal: 3000

  - poolID: "classic:casual3"
    strategy: "classic:poll"
    batchSize: 30
    internal: 3000
