// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: march.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryStatusResponse_Status int32

const (
	QueryStatusResponse_STATUS_UNKNOWN   QueryStatusResponse_Status = 0
	QueryStatusResponse_STATUS_WAITING   QueryStatusResponse_Status = 1
	QueryStatusResponse_STATUS_MATCHING  QueryStatusResponse_Status = 2
	QueryStatusResponse_STATUS_SUCCESS   QueryStatusResponse_Status = 3
	QueryStatusResponse_STATUS_CANCELLED QueryStatusResponse_Status = 4
)

// Enum value maps for QueryStatusResponse_Status.
var (
	QueryStatusResponse_Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_WAITING",
		2: "STATUS_MATCHING",
		3: "STATUS_SUCCESS",
		4: "STATUS_CANCELLED",
	}
	QueryStatusResponse_Status_value = map[string]int32{
		"STATUS_UNKNOWN":   0,
		"STATUS_WAITING":   1,
		"STATUS_MATCHING":  2,
		"STATUS_SUCCESS":   3,
		"STATUS_CANCELLED": 4,
	}
)

func (x QueryStatusResponse_Status) Enum() *QueryStatusResponse_Status {
	p := new(QueryStatusResponse_Status)
	*p = x
	return p
}

func (x QueryStatusResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryStatusResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_march_proto_enumTypes[0].Descriptor()
}

func (QueryStatusResponse_Status) Type() protoreflect.EnumType {
	return &file_march_proto_enumTypes[0]
}

func (x QueryStatusResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryStatusResponse_Status.Descriptor instead.
func (QueryStatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_march_proto_rawDescGZIP(), []int{5, 0}
}

type JoinQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`   // 必填，用户唯一 ID
	NodeID        string                 `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`   // connector 节点 ID（如 connector-001）
	Ranking       string                 `protobuf:"bytes,3,opt,name=ranking,proto3" json:"ranking,omitempty"` // 可选，如果客户端指定段位；否则由 march 查询用户信息
	TraceID       string                 `protobuf:"bytes,4,opt,name=traceID,proto3" json:"traceID,omitempty"` // 可选，用于链路跟踪/日志
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinQueueRequest) Reset() {
	*x = JoinQueueRequest{}
	mi := &file_march_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinQueueRequest) ProtoMessage() {}

func (x *JoinQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_march_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinQueueRequest.ProtoReflect.Descriptor instead.
func (*JoinQueueRequest) Descriptor() ([]byte, []int) {
	return file_march_proto_rawDescGZIP(), []int{0}
}

func (x *JoinQueueRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *JoinQueueRequest) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *JoinQueueRequest) GetRanking() string {
	if x != nil {
		return x.Ranking
	}
	return ""
}

func (x *JoinQueueRequest) GetTraceID() string {
	if x != nil {
		return x.TraceID
	}
	return ""
}

type JoinQueueResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	QueueID          string                 `protobuf:"bytes,3,opt,name=queueID,proto3" json:"queueID,omitempty"`                    // 可选，用于 QueryStatus
	EstimatedSeconds int32                  `protobuf:"varint,4,opt,name=estimatedSeconds,proto3" json:"estimatedSeconds,omitempty"` // 估计等待时间
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JoinQueueResponse) Reset() {
	*x = JoinQueueResponse{}
	mi := &file_march_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinQueueResponse) ProtoMessage() {}

func (x *JoinQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_march_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinQueueResponse.ProtoReflect.Descriptor instead.
func (*JoinQueueResponse) Descriptor() ([]byte, []int) {
	return file_march_proto_rawDescGZIP(), []int{1}
}

func (x *JoinQueueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinQueueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinQueueResponse) GetQueueID() string {
	if x != nil {
		return x.QueueID
	}
	return ""
}

func (x *JoinQueueResponse) GetEstimatedSeconds() int32 {
	if x != nil {
		return x.EstimatedSeconds
	}
	return 0
}

type LeaveQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	QueueID       string                 `protobuf:"bytes,2,opt,name=queueID,proto3" json:"queueID,omitempty"` // 与上面对应，也可以直接根据 userID 查询
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveQueueRequest) Reset() {
	*x = LeaveQueueRequest{}
	mi := &file_march_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveQueueRequest) ProtoMessage() {}

func (x *LeaveQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_march_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveQueueRequest.ProtoReflect.Descriptor instead.
func (*LeaveQueueRequest) Descriptor() ([]byte, []int) {
	return file_march_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveQueueRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *LeaveQueueRequest) GetQueueID() string {
	if x != nil {
		return x.QueueID
	}
	return ""
}

type LeaveQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveQueueResponse) Reset() {
	*x = LeaveQueueResponse{}
	mi := &file_march_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveQueueResponse) ProtoMessage() {}

func (x *LeaveQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_march_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveQueueResponse.ProtoReflect.Descriptor instead.
func (*LeaveQueueResponse) Descriptor() ([]byte, []int) {
	return file_march_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveQueueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LeaveQueueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QueryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	QueueID       string                 `protobuf:"bytes,2,opt,name=queueID,proto3" json:"queueID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStatusRequest) Reset() {
	*x = QueryStatusRequest{}
	mi := &file_march_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStatusRequest) ProtoMessage() {}

func (x *QueryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_march_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStatusRequest.ProtoReflect.Descriptor instead.
func (*QueryStatusRequest) Descriptor() ([]byte, []int) {
	return file_march_proto_rawDescGZIP(), []int{4}
}

func (x *QueryStatusRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *QueryStatusRequest) GetQueueID() string {
	if x != nil {
		return x.QueueID
	}
	return ""
}

type QueryStatusResponse struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	Status           QueryStatusResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=QueryStatusResponse_Status" json:"status,omitempty"`
	Position         int32                      `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"` // 排队位次，便于前端展示
	EstimatedSeconds int32                      `protobuf:"varint,3,opt,name=estimatedSeconds,proto3" json:"estimatedSeconds,omitempty"`
	GameNodeID       string                     `protobuf:"bytes,4,opt,name=gameNodeID,proto3" json:"gameNodeID,omitempty"` // 匹配成功后返回
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryStatusResponse) Reset() {
	*x = QueryStatusResponse{}
	mi := &file_march_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStatusResponse) ProtoMessage() {}

func (x *QueryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_march_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStatusResponse.ProtoReflect.Descriptor instead.
func (*QueryStatusResponse) Descriptor() ([]byte, []int) {
	return file_march_proto_rawDescGZIP(), []int{5}
}

func (x *QueryStatusResponse) GetStatus() QueryStatusResponse_Status {
	if x != nil {
		return x.Status
	}
	return QueryStatusResponse_STATUS_UNKNOWN
}

func (x *QueryStatusResponse) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *QueryStatusResponse) GetEstimatedSeconds() int32 {
	if x != nil {
		return x.EstimatedSeconds
	}
	return 0
}

func (x *QueryStatusResponse) GetGameNodeID() string {
	if x != nil {
		return x.GameNodeID
	}
	return ""
}

var File_march_proto protoreflect.FileDescriptor

const file_march_proto_rawDesc = "" +
	"\n" +
	"\vmarch.proto\"v\n" +
	"\x10JoinQueueRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x16\n" +
	"\x06nodeID\x18\x02 \x01(\tR\x06nodeID\x12\x18\n" +
	"\aranking\x18\x03 \x01(\tR\aranking\x12\x18\n" +
	"\atraceID\x18\x04 \x01(\tR\atraceID\"\x8d\x01\n" +
	"\x11JoinQueueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\aqueueID\x18\x03 \x01(\tR\aqueueID\x12*\n" +
	"\x10estimatedSeconds\x18\x04 \x01(\x05R\x10estimatedSeconds\"E\n" +
	"\x11LeaveQueueRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x18\n" +
	"\aqueueID\x18\x02 \x01(\tR\aqueueID\"H\n" +
	"\x12LeaveQueueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x12QueryStatusRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x18\n" +
	"\aqueueID\x18\x02 \x01(\tR\aqueueID\"\xa3\x02\n" +
	"\x13QueryStatusResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.QueryStatusResponse.StatusR\x06status\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\x12*\n" +
	"\x10estimatedSeconds\x18\x03 \x01(\x05R\x10estimatedSeconds\x12\x1e\n" +
	"\n" +
	"gameNodeID\x18\x04 \x01(\tR\n" +
	"gameNodeID\"o\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eSTATUS_WAITING\x10\x01\x12\x13\n" +
	"\x0fSTATUS_MATCHING\x10\x02\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x03\x12\x14\n" +
	"\x10STATUS_CANCELLED\x10\x042\xb3\x01\n" +
	"\fMatchService\x122\n" +
	"\tJoinQueue\x12\x11.JoinQueueRequest\x1a\x12.JoinQueueResponse\x125\n" +
	"\n" +
	"LeaveQueue\x12\x12.LeaveQueueRequest\x1a\x13.LeaveQueueResponse\x128\n" +
	"\vQueryStatus\x12\x13.QueryStatusRequest\x1a\x14.QueryStatusResponseB\rZ\vmarch/pb;pbb\x06proto3"

var (
	file_march_proto_rawDescOnce sync.Once
	file_march_proto_rawDescData []byte
)

func file_march_proto_rawDescGZIP() []byte {
	file_march_proto_rawDescOnce.Do(func() {
		file_march_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_march_proto_rawDesc), len(file_march_proto_rawDesc)))
	})
	return file_march_proto_rawDescData
}

var file_march_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_march_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_march_proto_goTypes = []any{
	(QueryStatusResponse_Status)(0), // 0: QueryStatusResponse.Status
	(*JoinQueueRequest)(nil),        // 1: JoinQueueRequest
	(*JoinQueueResponse)(nil),       // 2: JoinQueueResponse
	(*LeaveQueueRequest)(nil),       // 3: LeaveQueueRequest
	(*LeaveQueueResponse)(nil),      // 4: LeaveQueueResponse
	(*QueryStatusRequest)(nil),      // 5: QueryStatusRequest
	(*QueryStatusResponse)(nil),     // 6: QueryStatusResponse
}
var file_march_proto_depIdxs = []int32{
	0, // 0: QueryStatusResponse.status:type_name -> QueryStatusResponse.Status
	1, // 1: MatchService.JoinQueue:input_type -> JoinQueueRequest
	3, // 2: MatchService.LeaveQueue:input_type -> LeaveQueueRequest
	5, // 3: MatchService.QueryStatus:input_type -> QueryStatusRequest
	2, // 4: MatchService.JoinQueue:output_type -> JoinQueueResponse
	4, // 5: MatchService.LeaveQueue:output_type -> LeaveQueueResponse
	6, // 6: MatchService.QueryStatus:output_type -> QueryStatusResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_march_proto_init() }
func file_march_proto_init() {
	if File_march_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_march_proto_rawDesc), len(file_march_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_march_proto_goTypes,
		DependencyIndexes: file_march_proto_depIdxs,
		EnumInfos:         file_march_proto_enumTypes,
		MessageInfos:      file_march_proto_msgTypes,
	}.Build()
	File_march_proto = out.File
	file_march_proto_goTypes = nil
	file_march_proto_depIdxs = nil
}
