// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/envelope.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息信封（统一消息格式）
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         string                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`                           // 路由（如 "auth.login", "heartbeat.ping"）
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                       // 业务数据（序列化的 protobuf）
	ClientSeq     uint64                 `protobuf:"varint,3,opt,name=client_seq,json=clientSeq,proto3" json:"client_seq,omitempty"` // 请求序列号（用于请求-响应匹配）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetClientSeq() uint64 {
	if x != nil {
		return x.ClientSeq
	}
	return 0
}

var File_proto_envelope_proto protoreflect.FileDescriptor

const file_proto_envelope_proto_rawDesc = "" +
	"\n" +
	"\x14proto/envelope.proto\x12\rgomahjong.net\"Y\n" +
	"\bEnvelope\x12\x14\n" +
	"\x05route\x18\x01 \x01(\tR\x05route\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"client_seq\x18\x03 \x01(\x04R\tclientSeqB\x0fZ\rwebtest/protob\x06proto3"

var (
	file_proto_envelope_proto_rawDescOnce sync.Once
	file_proto_envelope_proto_rawDescData []byte
)

func file_proto_envelope_proto_rawDescGZIP() []byte {
	file_proto_envelope_proto_rawDescOnce.Do(func() {
		file_proto_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_envelope_proto_rawDesc), len(file_proto_envelope_proto_rawDesc)))
	})
	return file_proto_envelope_proto_rawDescData
}

var file_proto_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_envelope_proto_goTypes = []any{
	(*Envelope)(nil), // 0: gomahjong.net.Envelope
}
var file_proto_envelope_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_envelope_proto_init() }
func file_proto_envelope_proto_init() {
	if File_proto_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_envelope_proto_rawDesc), len(file_proto_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_envelope_proto_goTypes,
		DependencyIndexes: file_proto_envelope_proto_depIdxs,
		MessageInfos:      file_proto_envelope_proto_msgTypes,
	}.Build()
	File_proto_envelope_proto = out.File
	file_proto_envelope_proto_goTypes = nil
	file_proto_envelope_proto_depIdxs = nil
}
