// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/game_mahjong.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 牌
type Tile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"` // 牌的类型 (万、条、筒、风、箭等)
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`     // 牌的 ID (1-9 等)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tile) Reset() {
	*x = Tile{}
	mi := &file_proto_game_mahjong_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tile) ProtoMessage() {}

func (x *Tile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_mahjong_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tile.ProtoReflect.Descriptor instead.
func (*Tile) Descriptor() ([]byte, []int) {
	return file_proto_game_mahjong_proto_rawDescGZIP(), []int{0}
}

func (x *Tile) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Tile) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 出牌请求
type PlayTileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tile          *Tile                  `protobuf:"bytes,1,opt,name=tile,proto3" json:"tile,omitempty"` // 打出的牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayTileRequest) Reset() {
	*x = PlayTileRequest{}
	mi := &file_proto_game_mahjong_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayTileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayTileRequest) ProtoMessage() {}

func (x *PlayTileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_mahjong_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayTileRequest.ProtoReflect.Descriptor instead.
func (*PlayTileRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_mahjong_proto_rawDescGZIP(), []int{1}
}

func (x *PlayTileRequest) GetTile() *Tile {
	if x != nil {
		return x.Tile
	}
	return nil
}

// 游戏状态推送
type GameStatePush struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	HandTiles      []*Tile                `protobuf:"bytes,2,rep,name=hand_tiles,json=handTiles,proto3" json:"hand_tiles,omitempty"`                 // 手牌
	DiscardTiles   []*Tile                `protobuf:"bytes,3,rep,name=discard_tiles,json=discardTiles,proto3" json:"discard_tiles,omitempty"`        // 弃牌区
	RemainingTiles int32                  `protobuf:"varint,5,opt,name=remaining_tiles,json=remainingTiles,proto3" json:"remaining_tiles,omitempty"` // 剩余牌数
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GameStatePush) Reset() {
	*x = GameStatePush{}
	mi := &file_proto_game_mahjong_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStatePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStatePush) ProtoMessage() {}

func (x *GameStatePush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_mahjong_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStatePush.ProtoReflect.Descriptor instead.
func (*GameStatePush) Descriptor() ([]byte, []int) {
	return file_proto_game_mahjong_proto_rawDescGZIP(), []int{2}
}

func (x *GameStatePush) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *GameStatePush) GetHandTiles() []*Tile {
	if x != nil {
		return x.HandTiles
	}
	return nil
}

func (x *GameStatePush) GetDiscardTiles() []*Tile {
	if x != nil {
		return x.DiscardTiles
	}
	return nil
}

func (x *GameStatePush) GetRemainingTiles() int32 {
	if x != nil {
		return x.RemainingTiles
	}
	return 0
}

// Debug: 创建房间请求（跳过 march 匹配）
type DebugCreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EngineType    int32                  `protobuf:"varint,1,opt,name=engine_type,json=engineType,proto3" json:"engine_type,omitempty"` // 1: RiichiMahjong4P
	PlayerIds     []string               `protobuf:"bytes,2,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`     // 玩家 ID 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugCreateRoomRequest) Reset() {
	*x = DebugCreateRoomRequest{}
	mi := &file_proto_game_mahjong_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugCreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugCreateRoomRequest) ProtoMessage() {}

func (x *DebugCreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_mahjong_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugCreateRoomRequest.ProtoReflect.Descriptor instead.
func (*DebugCreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_mahjong_proto_rawDescGZIP(), []int{3}
}

func (x *DebugCreateRoomRequest) GetEngineType() int32 {
	if x != nil {
		return x.EngineType
	}
	return 0
}

func (x *DebugCreateRoomRequest) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

// Debug: 创建房间响应
type DebugCreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 创建成功的房间 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugCreateRoomResponse) Reset() {
	*x = DebugCreateRoomResponse{}
	mi := &file_proto_game_mahjong_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugCreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugCreateRoomResponse) ProtoMessage() {}

func (x *DebugCreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_mahjong_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugCreateRoomResponse.ProtoReflect.Descriptor instead.
func (*DebugCreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_mahjong_proto_rawDescGZIP(), []int{4}
}

func (x *DebugCreateRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

var File_proto_game_mahjong_proto protoreflect.FileDescriptor

const file_proto_game_mahjong_proto_rawDesc = "" +
	"\n" +
	"\x18proto/game_mahjong.proto\x12\x0egomahjong.game\"*\n" +
	"\x04Tile\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\";\n" +
	"\x0fPlayTileRequest\x12(\n" +
	"\x04tile\x18\x01 \x01(\v2\x14.gomahjong.game.TileR\x04tile\"\xc1\x01\n" +
	"\rGameStatePush\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x123\n" +
	"\n" +
	"hand_tiles\x18\x02 \x03(\v2\x14.gomahjong.game.TileR\thandTiles\x129\n" +
	"\rdiscard_tiles\x18\x03 \x03(\v2\x14.gomahjong.game.TileR\fdiscardTiles\x12'\n" +
	"\x0fremaining_tiles\x18\x05 \x01(\x05R\x0eremainingTiles\"X\n" +
	"\x16DebugCreateRoomRequest\x12\x1f\n" +
	"\vengine_type\x18\x01 \x01(\x05R\n" +
	"engineType\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\tR\tplayerIds\"2\n" +
	"\x17DebugCreateRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomIdB\x0fZ\rwebtest/protob\x06proto3"

var (
	file_proto_game_mahjong_proto_rawDescOnce sync.Once
	file_proto_game_mahjong_proto_rawDescData []byte
)

func file_proto_game_mahjong_proto_rawDescGZIP() []byte {
	file_proto_game_mahjong_proto_rawDescOnce.Do(func() {
		file_proto_game_mahjong_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_mahjong_proto_rawDesc), len(file_proto_game_mahjong_proto_rawDesc)))
	})
	return file_proto_game_mahjong_proto_rawDescData
}

var file_proto_game_mahjong_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_game_mahjong_proto_goTypes = []any{
	(*Tile)(nil),                    // 0: gomahjong.game.Tile
	(*PlayTileRequest)(nil),         // 1: gomahjong.game.PlayTileRequest
	(*GameStatePush)(nil),           // 2: gomahjong.game.GameStatePush
	(*DebugCreateRoomRequest)(nil),  // 3: gomahjong.game.DebugCreateRoomRequest
	(*DebugCreateRoomResponse)(nil), // 4: gomahjong.game.DebugCreateRoomResponse
}
var file_proto_game_mahjong_proto_depIdxs = []int32{
	0, // 0: gomahjong.game.PlayTileRequest.tile:type_name -> gomahjong.game.Tile
	0, // 1: gomahjong.game.GameStatePush.hand_tiles:type_name -> gomahjong.game.Tile
	0, // 2: gomahjong.game.GameStatePush.discard_tiles:type_name -> gomahjong.game.Tile
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_game_mahjong_proto_init() }
func file_proto_game_mahjong_proto_init() {
	if File_proto_game_mahjong_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_mahjong_proto_rawDesc), len(file_proto_game_mahjong_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_mahjong_proto_goTypes,
		DependencyIndexes: file_proto_game_mahjong_proto_depIdxs,
		MessageInfos:      file_proto_game_mahjong_proto_msgTypes,
	}.Build()
	File_proto_game_mahjong_proto = out.File
	file_proto_game_mahjong_proto_goTypes = nil
	file_proto_game_mahjong_proto_depIdxs = nil
}
