// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/game_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建房间请求
type CreateRoomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 玩家列表：userID -> connectorTopic
	// connectorTopic 用于推送消息给玩家所在的 connector 节点
	Players map[string]string `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 游戏引擎类型
	// 1: 日本麻将 4 人
	EngineType    int32 `protobuf:"varint,2,opt,name=engine_type,json=engineType,proto3" json:"engine_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_proto_game_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoomRequest) GetPlayers() map[string]string {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *CreateRoomRequest) GetEngineType() int32 {
	if x != nil {
		return x.EngineType
	}
	return 0
}

// 创建房间响应
type CreateRoomResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 房间 ID（成功时返回）
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// 消息（失败时返回错误原因）
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_proto_game_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_game_service_proto protoreflect.FileDescriptor

const file_proto_game_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/game_service.proto\x12\rgomahjong.rpc\"\xb9\x01\n" +
	"\x11CreateRoomRequest\x12G\n" +
	"\aplayers\x18\x01 \x03(\v2-.gomahjong.rpc.CreateRoomRequest.PlayersEntryR\aplayers\x12\x1f\n" +
	"\vengine_type\x18\x02 \x01(\x05R\n" +
	"engineType\x1a:\n" +
	"\fPlayersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\x12CreateRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2`\n" +
	"\vGameService\x12Q\n" +
	"\n" +
	"CreateRoom\x12 .gomahjong.rpc.CreateRoomRequest\x1a!.gomahjong.rpc.CreateRoomResponseB\x0fZ\rwebtest/protob\x06proto3"

var (
	file_proto_game_service_proto_rawDescOnce sync.Once
	file_proto_game_service_proto_rawDescData []byte
)

func file_proto_game_service_proto_rawDescGZIP() []byte {
	file_proto_game_service_proto_rawDescOnce.Do(func() {
		file_proto_game_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_service_proto_rawDesc), len(file_proto_game_service_proto_rawDesc)))
	})
	return file_proto_game_service_proto_rawDescData
}

var file_proto_game_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_game_service_proto_goTypes = []any{
	(*CreateRoomRequest)(nil),  // 0: gomahjong.rpc.CreateRoomRequest
	(*CreateRoomResponse)(nil), // 1: gomahjong.rpc.CreateRoomResponse
	nil,                        // 2: gomahjong.rpc.CreateRoomRequest.PlayersEntry
}
var file_proto_game_service_proto_depIdxs = []int32{
	2, // 0: gomahjong.rpc.CreateRoomRequest.players:type_name -> gomahjong.rpc.CreateRoomRequest.PlayersEntry
	0, // 1: gomahjong.rpc.GameService.CreateRoom:input_type -> gomahjong.rpc.CreateRoomRequest
	1, // 2: gomahjong.rpc.GameService.CreateRoom:output_type -> gomahjong.rpc.CreateRoomResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_game_service_proto_init() }
func file_proto_game_service_proto_init() {
	if File_proto_game_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_service_proto_rawDesc), len(file_proto_game_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_game_service_proto_goTypes,
		DependencyIndexes: file_proto_game_service_proto_depIdxs,
		MessageInfos:      file_proto_game_service_proto_msgTypes,
	}.Build()
	File_proto_game_service_proto = out.File
	file_proto_game_service_proto_goTypes = nil
	file_proto_game_service_proto_depIdxs = nil
}
