// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/heartbeat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 心跳请求
type HeartbeatPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 客户端时间戳（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPing) Reset() {
	*x = HeartbeatPing{}
	mi := &file_proto_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPing) ProtoMessage() {}

func (x *HeartbeatPing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPing.ProtoReflect.Descriptor instead.
func (*HeartbeatPing) Descriptor() ([]byte, []int) {
	return file_proto_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatPing) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 心跳响应
type HeartbeatPong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // 服务端时间戳
	ServerSeq     uint64                 `protobuf:"varint,2,opt,name=server_seq,json=serverSeq,proto3" json:"server_seq,omitempty"` // 服务端序列号（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPong) Reset() {
	*x = HeartbeatPong{}
	mi := &file_proto_heartbeat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPong) ProtoMessage() {}

func (x *HeartbeatPong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heartbeat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPong.ProtoReflect.Descriptor instead.
func (*HeartbeatPong) Descriptor() ([]byte, []int) {
	return file_proto_heartbeat_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatPong) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatPong) GetServerSeq() uint64 {
	if x != nil {
		return x.ServerSeq
	}
	return 0
}

var File_proto_heartbeat_proto protoreflect.FileDescriptor

const file_proto_heartbeat_proto_rawDesc = "" +
	"\n" +
	"\x15proto/heartbeat.proto\x12\rgomahjong.net\"-\n" +
	"\rHeartbeatPing\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\"L\n" +
	"\rHeartbeatPong\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12\x1d\n" +
	"\n" +
	"server_seq\x18\x02 \x01(\x04R\tserverSeqB\x0fZ\rwebtest/protob\x06proto3"

var (
	file_proto_heartbeat_proto_rawDescOnce sync.Once
	file_proto_heartbeat_proto_rawDescData []byte
)

func file_proto_heartbeat_proto_rawDescGZIP() []byte {
	file_proto_heartbeat_proto_rawDescOnce.Do(func() {
		file_proto_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_heartbeat_proto_rawDesc), len(file_proto_heartbeat_proto_rawDesc)))
	})
	return file_proto_heartbeat_proto_rawDescData
}

var file_proto_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_heartbeat_proto_goTypes = []any{
	(*HeartbeatPing)(nil), // 0: gomahjong.net.HeartbeatPing
	(*HeartbeatPong)(nil), // 1: gomahjong.net.HeartbeatPong
}
var file_proto_heartbeat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_heartbeat_proto_init() }
func file_proto_heartbeat_proto_init() {
	if File_proto_heartbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_heartbeat_proto_rawDesc), len(file_proto_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_heartbeat_proto_goTypes,
		DependencyIndexes: file_proto_heartbeat_proto_depIdxs,
		MessageInfos:      file_proto_heartbeat_proto_msgTypes,
	}.Build()
	File_proto_heartbeat_proto = out.File
	file_proto_heartbeat_proto_goTypes = nil
	file_proto_heartbeat_proto_depIdxs = nil
}
