appName: GoMahjong-auth-service
serverType: auth
httpPort: 8087
wsPort: 8088
metricPort: 9097

log:
  level: info
  path: ./logs
etcd:
  addrs: ["127.0.0.1:2379"]
  register:
    addr: 127.0.0.1:11501
    domain: auth
    version: v1
    weight: 10
    ttl: 30
  rwTimeout: 3
  dialTimeout: 3

database:
  mongo:
    url: mongodb://localhost:27017
    db: go_mahjong
    username: ""
    password: ""
    minPoolSize: 10
    maxPoolSize: 100
  redis:
    addr: localhost:6379
    clusterAddrs: []
    password: ""
    poolSize: 100
    minIdleConns: 10
    host: localhost
    port: 6379

nats:
  url: nats://127.0.0.1:4222
